framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations/overrides'
            - '%kernel.project_dir%/translations'
        fallbacks:
            - '%locale%'
