_ajax:
    resource: routes/ajax.yml

_ban:
    resource: routes/ban.yml

_comment:
    resource: routes/comment.yml

_forum:
    resource: routes/forum.yml

_front:
    resource: routes/front.yml

_message:
    resource: routes/message.yml

_reset_password:
    resource: routes/reset_password.yml

_security:
    resource: routes/security.yml

_submission:
    resource: routes/submission.yml

_theme:
    resource: routes/theme.yml

_user:
    resource: routes/user.yml

_wiki:
    resource: routes/wiki.yml

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix: /_t/

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_trailing_slash_redirect:
    controller: Raddit\AppBundle\Controller\RedirectingController::removeTrailingSlash
    path: /{url}
    requirements: { url: '.*/$' }
