raddit_app_routing:
    resource: "@RadditAppBundle/Resources/config/routing.yml"

raddit_app_forum_routing:
    resource: "@RadditAppBundle/Resources/config/forum_routing.yml"
    prefix: /f

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix: /_t/

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
