raddit_app_front:
    defaults: { _controller: RadditAppBundle:Submission:frontPage }
    path: /
    methods: [GET]

raddit_app_forum:
    defaults: { _controller: RadditAppBundle:Submission:forum }
    path: /f/{name}/
    methods: [GET]

raddit_app_comments:
    defaults: { _controller: RadditAppBundle:Submission:commentPage }
    path: /f/{forum_name}/{submission_id}/
    methods: [GET]

raddit_app_comment:
    defaults: { _controller: RadditAppBundle:Submission:commentPermalink }
    path: /f/{forum_name}/{submission_id}/comment/{comment_id}/
    methods: [GET, POST]

raddit_app_user:
    defaults: { _controller: RadditAppBundle:User:userPage }
    path: /user/{username}
    methods: [GET]

raddit_app_registration:
    defaults: { _controller: RadditAppBundle:User:registration }
    path: /registration
    methods: [GET, POST]

raddit_app_login:
    defaults: { _controller: RadditAppBundle:Security:login }
    path: /login
    methods: [GET]

raddit_app_login_check:
    path: /login_check
    methods: [POST]

raddit_app_log_out:
    path: /log_out
