raddit_app_routing:
    resource: "@RadditAppBundle/Resources/config/routing.yml"

raddit_app_forum_routing:
    resource: "@RadditAppBundle/Resources/config/forum_routing.yml"
    prefix: /f/{forum_name}/

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix: /_t/

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
