_raddit_app_ajax:
    resource: routes/ajax.yml

_raddit_app_ban:
    resource: routes/ban.yml

_raddit_app_comment:
    resource: routes/comment.yml

_raddit_app_forum:
    resource: routes/forum.yml

_raddit_app_front:
    resource: routes/front.yml

_raddit_app_message:
    resource: routes/message.yml

_raddit_app_reset_password:
    resource: routes/reset_password.yml

_raddit_app_security:
    resource: routes/security.yml

_raddit_app_submission:
    resource: routes/submission.yml

_raddit_app_theme:
    resource: routes/theme.yml

_raddit_app_user:
    resource: routes/user.yml

_raddit_app_wiki:
    resource: routes/wiki.yml

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"
    prefix: /_t/

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

_gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    prefix: /_gcb

_fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_trailing_slash_redirect:
    defaults: { _controller: RadditAppBundle:Redirecting:removeTrailingSlash }
    path: /{url}
    requirements: { url: '.*/$' }
