security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        AppBundle\Entity\User:         bcrypt
        AppBundle\Form\Model\UserData: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            logout_on_user_change: true

            # this is enabled for unit tests
            http_basic: ~

            form_login:
                csrf_token_generator: security.csrf.token_manager
                check_path: login_check
                login_path: login

            logout:
                csrf_parameter: token
                csrf_token_generator: security.csrf.token_manager
                path: log_out

            remember_me:
                secret: "%secret"
                always_remember_me: true

            user_checker: AppBundle\Security\UserChecker

    role_hierarchy:
        ROLE_ADMIN:        [ROLE_TRUSTED_USER, ROLE_USER]
        ROLE_TRUSTED_USER: [ROLE_USER]
