#
# This file describes non-forum routes, i.e. routes that do not have an /f/
# prefix.
#

raddit_app_front:
    defaults: { _controller: RadditAppBundle:Front:front, sortBy: hot, page: 1 }
    path: /{sortBy}/{page}
    methods: [GET]
    requirements: { sortBy: hot|new|top|controversial, page: \d+ }

raddit_app_all:
    defaults: { _controller: RadditAppBundle:Front:all, sortBy: hot, page: 1 }
    path: /all/{sortBy}/{page}
    methods: [GET]
    requirements: { sortBy: hot|new|top|controversial, page: \d+ }

raddit_app_featured:
    defaults: { _controller: RadditAppBundle:Front:featured, sortBy: hot, page: 1}
    path: /featured/{sortBy}/{page}
    methods: [GET]
    requirements: { sortBy: hot|new|top|controversial, page: \d+ }

raddit_app_user:
    defaults: { _controller: RadditAppBundle:User:userPage }
    path: /user/{username}
    methods: [GET]

raddit_app_user_shortcut:
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: raddit_app_user }
    path: /u/{username}
    methods: [GET]

raddit_app_user_submissions:
    defaults: { _controller: RadditAppBundle:User:submissions, page: 1 }
    path: /user/{username}/submissions/{page}
    methods: [GET]
    requirements: { page: \d+ }

raddit_app_user_comments:
    defaults: { _controller: RadditAppBundle:User:comments, page: 1 }
    path: /user/{username}/comments/{page}
    methods: [GET]
    requirements: { page: \d+ }

raddit_app_edit_user:
    defaults: { _controller: RadditAppBundle:User:editUser }
    path: /edit_user/{username}
    methods: [GET, POST]

raddit_app_user_settings:
    defaults: { _controller: RadditAppBundle:User:userSettings }
    path: /user_settings/{username}
    methods: [GET, POST]

raddit_app_registration:
    defaults: { _controller: RadditAppBundle:User:registration }
    path: /registration
    methods: [GET, POST]

raddit_app_login:
    defaults: { _controller: RadditAppBundle:Security:login }
    path: /login
    methods: [GET]

raddit_app_create_forum:
    defaults: { _controller: RadditAppBundle:Forum:createForum }
    path: /create_forum
    methods: [GET, POST]

raddit_app_forum_list:
    defaults: { _controller: RadditAppBundle:Forum:list, page: 1, sortBy: by_submissions }
    path: /forums/{sortBy}/{page}
    methods: [GET]
    requirements: { forums: \d+, sortBy: by_name|by_title|by_subscribers|by_submissions }

raddit_app_forums_by_category:
    defaults: { _controller: RadditAppBundle:Forum:listCategories }
    path: /forums/by_category
    methods: [GET]

raddit_app_submit:
    defaults: { _controller: RadditAppBundle:Submission:submit, forum_name: null }
    path: /submit/{forum_name}
    methods: [GET, POST]

raddit_app_comment_form:
    defaults: { _controller: RadditAppBundle:Comment:commentForm, comment_id: null }
    methods: [GET]
    path: /comment_form/{forumName}/{submissionId}/{commentId}
    requirements: { submissionId: \d+, commentId: \d+ }

raddit_app_comment_vote:
    defaults:
        _controller: RadditAppBundle:Vote:vote
        _format: html
        entityClass: Raddit\AppBundle\Entity\Comment
    path: /cv/{id}.{_format}
    methods: [POST]
    requirements: { _format: html|json }

raddit_app_submission_vote:
    defaults:
        _controller: RadditAppBundle:Vote:vote
        _format: html
        entityClass: Raddit\AppBundle\Entity\Submission
    path: /sv/{id}.{_format}
    methods: [POST]
    requirements: { _format: html|json }

raddit_app_delete_comment:
    defaults: { _controller: RadditAppBundle:Comment:deleteComment }
    path: /dc/{id}
    methods: [POST]

raddit_app_softdelete_comment:
    defaults: { _controller: RadditAppBundle:Comment:softDeleteComment }
    path: /sdc/{id}
    methods: [POST]

raddit_app_subscribe:
    defaults: { _controller: RadditAppBundle:Forum:subscribe, action: subscribe }
    path: /sub/{id}
    methods: [POST]

raddit_app_unsubscribe:
    defaults: { _controller: RadditAppBundle:Forum:subscribe, action: unsubscribe }
    path: /unsub/{id}
    methods: [POST]

raddit_app_stylesheets:
    defaults: { _controller: RadditAppBundle:Stylesheet:list, page: 1 }
    path: /stylesheets/{page}
    methods: [GET]
    requirements: { page: \d+ }

raddit_app_create_stylesheet:
    defaults: { _controller: RadditAppBundle:Stylesheet:create }
    path: /create_stylesheet
    methods: [GET, POST]

raddit_app_edit_stylesheet:
    defaults: { _controller: RadditAppBundle:Stylesheet:edit }
    path: /edit_stylesheet/{id}
    methods: [GET, POST]

raddit_app_raw_stylesheet:
    defaults: { _controller: RadditAppBundle:Stylesheet:raw, _format: css }
    path: /user_style/{id}.css
    methods: [GET]

raddit_app_fetch_title:
    defaults: { _controller: RadditAppBundle:Ajax:fetchTitle, _format: json }
    path: /ft.json
    methods: [POST]
    options: { expose: true }

raddit_app_markdown_preview:
    defaults: { _controller: RadditAppBundle:Ajax:markdownPreview }
    path: /md
    methods: [POST]
    options: { expose: true }

raddit_app_request_password_reset:
    defaults: { _controller: RadditAppBundle:ResetPassword:requestReset }
    path: /reset_password
    methods: [GET, POST]

raddit_app_password_reset:
    defaults: { _controller: RadditAppBundle:ResetPassword:reset }
    path: /reset_password/{id}/{expires}/{checksum}
    methods: [GET, POST]

raddit_app_inbox:
    defaults: { _controller: RadditAppBundle:User:inbox, page: 1 }
    path: /inbox/{page}
    methods: [GET]
    requirements: { page: \d+ }

raddit_app_clear_inbox:
    defaults: { _controller: RadditAppBundle:User:clearInbox, _format: html }
    path: /clear_inbox.{_format}
    methods: [POST]
    requirements: { _format: html|json }

raddit_app_bans:
    defaults: { _controller: RadditAppBundle:Ban:list, page: 1 }
    path: /bans/{page}
    methods: [GET]
    requirements: { page: \d+ }

raddit_app_add_ban:
    defaults: { _controller: RadditAppBundle:Ban:add }
    path: /add_ban
    methods: [GET, POST]

raddit_app_remove_bans:
    defaults: { _controller: RadditAppBundle:Ban:remove }
    path: /remove_bans
    methods: [POST]

raddit_app_ban_ip_by_submission:
    defaults:
        _controller: RadditAppBundle:Ban:redirect
        entityClass: RadditAppBundle:Submission
    methods: [GET]
    path: /ban_by_submission/{id}

raddit_app_ban_ip_by_comment:
    defaults:
        _controller: RadditAppBundle:Ban:redirect
        entityClass: RadditAppBundle:Comment
    path: /ban_by_comment/{id}
    methods: [GET]

raddit_app_message_list:
    defaults: { _controller: RadditAppBundle:Message:list, page: 1 }
    path: /messages/{page}
    methods: [GET]

raddit_app_message:
    defaults: { _controller: RadditAppBundle:Message:message }
    path: /message/{id}
    methods: [GET, POST]

raddit_app_compose_message:
    defaults: { _controller: RadditAppBundle:Message:compose }
    path: /compose_message/{username}
    methods: [GET, POST]

raddit_app_wiki:
    defaults: { _controller: RadditAppBundle:Wiki:wiki, path: index }
    path: /wiki/{path}
    methods: [GET]
    requirements: { path: "%wiki_page_regex%" }

raddit_app_wiki_create:
    defaults: { _controller: RadditAppBundle:Wiki:create }
    path: /wiki/_create/{path}
    methods: [GET, POST]
    requirements: { path: "%wiki_page_regex%" }

raddit_app_wiki_edit:
    defaults: { _controller: RadditAppBundle:Wiki:edit }
    path: /wiki/_edit/{path}
    methods: [GET, POST]
    requirements: { path: "%wiki_page_regex%" }

raddit_app_wiki_history:
    defaults: { _controller: RadditAppBundle:Wiki:history, page: 1 }
    path: /wiki/_history/{path}/{page}
    methods: [GET]
    requirements: { path: "%wiki_page_regex%" }

raddit_app_wiki_all:
    defaults: { _controller: RadditAppBundle:Wiki:all, page: 1 }
    path: /wiki/_all/{page}
    methods: [GET]

raddit_app_wiki_revision:
    defaults: { _controller: RadditAppBundle:Wiki:revision }
    path: /wiki/_revision/{id}
    methods: [GET]

raddit_app_login_check:
    path: /login_check
    methods: [POST]

raddit_app_log_out:
    path: /log_out

raddit_app_2fa_post:
    path: /
    methods: [POST]
