#
# This file describes non-forum routes, i.e. routes that do not have an /f/
# prefix.
#

raddit_app_front:
    defaults: { _controller: RadditAppBundle:Submission:frontPage }
    path: /
    methods: [GET]

raddit_app_user:
    defaults: { _controller: RadditAppBundle:User:userPage }
    path: /user/{username}
    methods: [GET]

raddit_app_edit_user:
    defaults: { _controller: RadditAppBundle:User:editUser }
    path: /edit_user/{username}
    methods: [GET, POST]

raddit_app_registration:
    defaults: { _controller: RadditAppBundle:User:registration }
    path: /registration
    methods: [GET, POST]

raddit_app_login:
    defaults: { _controller: RadditAppBundle:Security:login }
    path: /login
    methods: [GET]

raddit_app_create_forum:
    defaults: { _controller: RadditAppBundle:Forum:createForum }
    path: /create_forum
    methods: [GET, POST]

raddit_app_comment_vote:
    defaults:
        _controller: RadditAppBundle:Vote:vote
        entityClass: Raddit\AppBundle\Entity\Comment
    path: /cv/{id}
    methods: [POST]

raddit_app_submission_vote:
    defaults:
        _controller: RadditAppBundle:Vote:vote
        entityClass: Raddit\AppBundle\Entity\Submission
    path: /sv/{id}
    methods: [POST]

raddit_app_delete_comment:
    defaults: { _controller: RadditAppBundle:Comment:deleteComment }
    path: /dc/{id}
    methods: [POST]

raddit_app_softdelete_comment:
    defaults: { _controller: RadditAppBundle:Comment:softDeleteComment }
    path: /sdc/{id}
    methods: [POST]

raddit_app_login_check:
    path: /login_check
    methods: [POST]

raddit_app_log_out:
    path: /log_out
