# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

# Symfony 3.3 naming convention
# http://symfony.com/blog/new-in-symfony-3-3-optional-class-for-named-services
services:
    Raddit\AppBundle\Form\ForumType:
        class: Raddit\AppBundle\Form\ForumType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type }

    Raddit\AppBundle\Form\UserType:
        class: Raddit\AppBundle\Form\UserType
        arguments: ["@security.password_encoder"]
        tags:
            - { name: form.type }

    Raddit\AppBundle\EventListener\AjaxListener:
        class: Raddit\AppBundle\EventListener\AjaxListener
        tags:
            - { name: kernel.event_subscriber }

    Raddit\AppBundle\EventListener\LocaleListener:
        class: Raddit\AppBundle\EventListener\LocaleListener
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 15 }
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    Raddit\AppBundle\Security\Voter\CommentVoter:
        class: Raddit\AppBundle\Security\Voter\CommentVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    Raddit\AppBundle\Security\Voter\ForumVoter:
        class: Raddit\AppBundle\Security\Voter\ForumVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    Raddit\AppBundle\Security\Voter\SubmissionVoter:
        class: Raddit\AppBundle\Security\Voter\SubmissionVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    Raddit\AppBundle\Security\Voter\UserVoter:
        class: Raddit\AppBundle\Security\Voter\UserVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false

    Raddit\AppBundle\Twig\AppExtension:
        class: Raddit\AppBundle\Twig\AppExtension
        calls:
            - [setSiteName, ["%site_name%"]]
        tags:
            - { name: twig.extension }
        public: false
