# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    raddit_app.site_name: Raddit

services:
    raddit_app.form.user_type:
        class: Raddit\AppBundle\Form\UserType
        arguments: ["@security.password_encoder"]
        tags:
            - { name: form.type }

    raddit_app.event_listener.ajax_listener:
        class: Raddit\AppBundle\EventListener\AjaxListener
        tags:
            - { name: kernel.event_subscriber }

    raddit_app.event_listener.update_canonical_fields_listener:
        class: Raddit\AppBundle\EventListener\UpdateCanonicalFieldsListener
        tags:
            - { name: doctrine.event_subscriber }

    raddit_app.security.voter.comment_voter:
        class: Raddit\AppBundle\Security\Voter\CommentVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }

    raddit_app.security.voter.user_voter:
        class: Raddit\AppBundle\Security\Voter\UserVoter
        arguments: ["@security.access.decision_manager"]
        tags:
            - { name: security.voter }

    raddit_app.twig.app_extension:
        class: Raddit\AppBundle\Twig\AppExtension
        calls:
            - [setSiteName, ["%raddit_app.site_name%"]]
        tags:
            - { name: twig.extension }
