# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    markdown_cache_time: 86400

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Raddit\AppBundle\:
        resource: '../../*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../{Entity,Repository}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    Raddit\AppBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Raddit\AppBundle\EventListener\AttachIpToEntityListener:
        arguments: ["@request_stack"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Raddit\AppBundle\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 15 }
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    Raddit\AppBundle\EventListener\SubmissionImageListener:
        calls:
            - [setLogger, ["@logger"]]
        arguments: ["@doctrine.orm.entity_manager", "@request_stack", "@validator"]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: kernel.event_listener, event: kernel.terminate }

    Raddit\AppBundle\EventListener\SubmissionRankListener:
        tags:
            - { name: doctrine.event_subscriber }

    Raddit\AppBundle\Repository\BanRepository:
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: [Raddit\AppBundle\Entity\Ban]

    Raddit\AppBundle\Repository\UserRepository:
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: [Raddit\AppBundle\Entity\User]

    Raddit\AppBundle\Twig\AppExtension:
        calls:
            - [setSiteName, ["%site_name%"]]

    Raddit\AppBundle\Utils\MarkdownConverter:
        factory: [Raddit\AppBundle\Utils\MarkdownConverter, createInstance]
        lazy: true

    Raddit\AppBundle\Utils\CachedMarkdownConverter:
        calls:
            - [setExpiresAfter, ["%markdown_cache_time%"]]
        lazy: true


    ## Misc

    Doctrine\DBAL\Connection: "@doctrine.dbal.default_connection"

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
