fetch_title:
    defaults: { _controller: RadditAppBundle:Ajax:fetchTitle, _format: json }
    path: /ft.json
    methods: [POST]
    options: { expose: true }

markdown_preview:
    defaults: { _controller: RadditAppBundle:Ajax:markdownPreview }
    path: /md
    methods: [POST]
    options: { expose: true }
