bans:
    controller: Raddit\AppBundle\Controller\BanController::list
    defaults: { page: 1 }
    path: /bans/{page}
    methods: [GET]
    requirements: { page: \d+ }

add_ban:
    controller: Raddit\AppBundle\Controller\BanController::add
    path: /add_ban
    methods: [GET, POST]

remove_bans:
    controller: Raddit\AppBundle\Controller\BanController::remove
    path: /remove_bans
    methods: [POST]

ban_ip_by_submission:
    controller: Raddit\AppBundle\Controller\BanController::redirectToBanForm
    defaults: { entityClass: Raddit\AppBundle\Entity\Submission }
    methods: [GET]
    path: /ban_by_submission/{id}

ban_ip_by_comment:
    controller: Raddit\AppBundle\Controller\BanController::redirectToBanForm
    defaults: { entityClass: Raddit\AppBundle\Entity\Comment }
    path: /ban_by_comment/{id}
    methods: [GET]
