user_bans:
    controller: AppBundle\Controller\BanController::userBans
    defaults: { page: 1 }
    path: /bans/{page}
    methods: [GET]
    requirements: { page: \d+ }

ban_user:
    controller: AppBundle\Controller\BanController::banUser
    methods: [GET, POST]
    path: /bans/ban_user/{username}

unban_user:
    controller: AppBundle\Controller\BanController::unbanUser
    methods: [GET, POST]
    path: /bans/unban_user/{username}

ip_bans:
    controller: AppBundle\Controller\BanController::ipBans
    defaults: { page: 1 }
    path: /bans/by_ip/{page}
    methods: [GET]
    requirements: { page: \d+ }

ban_ip:
    controller: AppBundle\Controller\BanController::banIp
    path: /bans/ban_ip
    methods: [GET, POST]

unban_ips:
    controller: AppBundle\Controller\BanController::unbanIps
    path: /bans/unban_ips
    methods: [POST]

ban_by_submission:
    controller: AppBundle\Controller\BanController::redirectToBanForm
    defaults: { entityClass: AppBundle\Entity\Submission }
    methods: [GET]
    path: /bans/ban_by_submission/{id}

ban_by_comment:
    controller: AppBundle\Controller\BanController::redirectToBanForm
    defaults: { entityClass: AppBundle\Entity\Comment }
    path: /bans/ban_by_comment/{id}
    methods: [GET]
