raddit_app_message_list:
    defaults: { _controller: RadditAppBundle:Message:list, page: 1 }
    path: /messages/{page}
    methods: [GET]

raddit_app_message:
    defaults: { _controller: RadditAppBundle:Message:message }
    path: /message/{id}
    methods: [GET]

raddit_app_compose_message:
    defaults: { _controller: RadditAppBundle:Message:compose }
    path: /compose_message/{username}
    methods: [GET, POST]

raddit_app_reply_to_message:
    defaults: { _controller: RadditAppBundle:Message:reply }
    path: /message_reply/{id}
    methods: [POST]
