request_password_reset:
    defaults: { _controller: RadditAppBundle:ResetPassword:requestReset }
    path: /reset_password
    methods: [GET, POST]

password_reset:
    defaults: { _controller: RadditAppBundle:ResetPassword:reset }
    path: /reset_password/{id}/{expires}/{checksum}
    methods: [GET, POST]
    requirements: { id: \d+, expires: \d+, checksum: '[0-9a-f]+' }
