login:
    defaults: { _controller: RadditAppBundle:Security:login }
    path: /login
    methods: [GET]

login_check:
    path: /login_check
    methods: [POST]

log_out:
    path: /log_out

2fa_post:
    path: /
    methods: [POST]
